require('dotenv').config();
import Head from "next/head";
import styled from 'styled-components';
import {useState, useEffect, useRef} from 'react';
// import Day_Quote from "@/components/Day_Quote";
import firebase_app from "@/library/firebaseConfig";
import database from "@/library/firebaseConfig";
import NavBar from "@/components/NavBar";
import { createGlobalStyle } from 'styled-components';
import MyGlobalStyle from "@/components/GlobalStyle";

// This file is the main page of the website. It will contain a brief description of the website, a motivational quote, and a button to sign up.
// my goal here was to have a simple yet aesthetically pleasing website, acting as a hub for the user to navigate to other pages.


export default function Home() {
  // State variables: 
  // quote: the motivational quote that will be displayed on the page, first API call
  const [quote, setQuote] = useState("Motivational Quote Here");
  useEffect(() => {
    fetchQuotes();
  }, []);
  // Fetch the quote from the API (code given by Omar)
  const fetchQuotes = async () => {
    try {
      console.log("Fetching the quote")
      const response = await fetch('/api/quote');
      const data = await response.json();
      setQuote(data.quote);
      console.log("Fetched!");
    } catch (error) {
      console.error('Error fetching quotes:', error);
    }
}


  return (
    <>
      <Head>
        {/* Meta-Information */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyGlobalStyle/>
      <ParentContainer>
        <NavBar/>
        <BodyContainer>
            <Description>
                <SmallerTitleContainer> Embark On Your Fitness Journey</SmallerTitleContainer>
                <p>
                    Discover personalized workout plans, track your progress, and join challenges to stay motivated alongside a community 
                    of fitness enthusiasts.</p>
                <GetStartedButton>
                    <StyledLink href="/signup" >Get Started</StyledLink>
                </GetStartedButton>
            </Description>
            <ImgAndTitleContainer>
            <ImgContainer>
                <Image src = "FitQuestLogoV4.jpg"/>
            </ImgContainer> <TitleContainer>FitQuest</TitleContainer></ImgAndTitleContainer>
            <Description>
                <SmallerTitleContainer>Inspiration For You</SmallerTitleContainer>
                <p>{quote}</p>
                {/* <Day_Quote/> */}
            </Description>
    </BodyContainer>
      </ParentContainer>

  

    </>
  );
}



// The styled components below are used to style the elements of the page.
// Some elements are somewhat redundant (i.e the usage of Description in several files), but they often had small yet impactful
// differences, and I decided it would be more worth my time to work on the quality of the website rather than try and 
// modularize the code more.

const ParentContainer = styled.div`
// height: 100%;
font-family: 'Roboto', sans-serif;
  // color: white;
  background-color: #f2f2e6;  //very light grey

//   color: Navy;
`

const StyledLink = styled.a`
  color: inherit;
  text-decoration: none;
`;

const TitleContainer = styled.div`
font-family: 'Roboto Serif', serif;
font-weight: 700;
font-style: italic;
font-size: 5.0vw;
font-curve: 1.5vw;
padding: 3vw;
align-items: center;
justify-content: center;
text-align: center;
font-weight: bold;
color: #FC984E;
`;

const SmallerTitleContainer = styled.div`
font-family: 'Roboto Serif', serif;
font-weight: 400;
font-style: bold;
font-size: 2.0vw;
font-curve: 1.5vw;
// padding: 3vw;
padding-bottom: .5vw;
align-items: center;
justify-content: center;
text-align: center;
font-weight: bold;
// color: #FC984E;
`;

const BodyContainer = styled.div`
  display: flex;
  justify-content: space-between;
  flex-direction: row;
  align-items: flex-start;
 
  height: 100%;
  background-color: #f2f2e6;  //very light grey
  padding: 0vw;
  padding-left: 3vw;
  padding-right: 3vw;
  overflow: hidden;
  position: static;
  overflow-x: auto;  // Add horizontal scrolling when children overflow
  margin-top: 0;

  
`;

const GetStartedButton = styled.button`
  display: inline-block;
  transition: all 0.2s ease-in;
  position: relative;
  overflow: hidden;
  z-index: 1;
  color: #090909;
  padding: 0.7em 1.7em;
  cursor: pointer;
  font-size: 1.2vw;
  margin-top: 1.5vw;
  font-weight: bold;
  border-radius: 0.8em;
  background: #e8e8e8;
  border: 3px solid #e8e8e8;
  box-shadow: 6px 6px 12px #c5c5c5, -6px -6px 12px #ffffff;

  &:active {
    color: #FC984E;
    box-shadow: inset 4px 4px 12px #c5c5c5, inset -4px -4px 12px #ffffff;
  }

  &:before, &:after {
    content: "";
    position: absolute;
    left: 50%;
    transform: translateX(-50%) scaleY(1) scaleX(1.25);
    top: 100%;
    width: 140%;
    height: 180%;
    background-color: rgba(0, 0, 0, 0.05);
    border-radius: 50%;
    display: block;
    transition: all 0.5s 0.1s cubic-bezier(0.55, 0, 0.1, 1);
    z-index: -1;
  }

  &:after {
    left: 55%;
    transform: translateX(-50%) scaleY(1) scaleX(1.45);
    top: 180%;
    width: 160%;
    height: 190%;
    background-color: #FC984E;
  }

  &:hover {
    color: #ffffff;
    border: 1px solid black;

    &:before {
      top: -35%;
      background-color: #9094ec;
      transform: translateX(-50%) scaleY(1.3) scaleX(0.8);
    }

    &:after {
      top: -45%;
      background-color: #FC984E;
      transform: translateX(-50%) scaleY(1.3) scaleX(0.8);
    }
  }
`;



const ImgContainer = styled.div`
    // display: flex;
    // justify-content: center;
    // border-radius: 3%;
    align-items: center;
    // transform: scale(1.0);
    // margin-top: 2vw;
    // box-shadow: 0 0 10px rgba(0, 0, 0, .3); 
    width: 24%;
    height: 20vw;     
    // background-color: #042131;
    // padding: 3vw;
    // border-top-left-radius: 10px;
    // border-top-right-radius: 10px;
    margin-bottom: 20vw;
    position: static;


`;
const ImgAndTitleContainer = styled.div`
  display: flex;
  flex-direction: column;
  flex: 80% 20%;
  width: 24%;
  height: 20vw;   
`;

const Image = styled.img`
  width: inherit;
  height: inherit;
  transform: inherit;
  position: absolute;
  top: inherit;
  left: inherit;
  transform: scale(1.4);
  
`;

const Description = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justfiy-content: center;
  height: 50%;
 
  boxwidth-shadow: 0 0 10px rgba(0, 0, 0, .3); 
  border-radius: 3%;

  width: 25%;
  padding: 3vw;
  
  font-size: 2.0vw;
  font-size: max(2.0vw, 16px); // Set the minimum font size to 16px

  font-family: 'Roboto', sans-serif;

  flex-shrink: 0;
  position: static;

`;
