import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";               
import styled from 'styled-components';


import NavBar from "@/components/NavBar";



// importing for a link to another page
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
// npm run dev


// Set all styled components 
const Container = styled.div`
  color: green;
`




const ParentContainer = styled.div`
*{
  // padding: 0;
  flex-direction: row;
  font: Roboto;
}
`


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* This h1 is a LINK to the test JS file  */}
      {/* {/* <h1><Link href="/test">Click to go to Dashboard</Link> </h1> */}

      <ParentContainer>
        <NavBar/>

      <TitleContainer> Welcome To FitQuest!</TitleContainer>
      <BodyContainer>
        <DescriptionAndImageContainer>
          <Description>
              <h1>About Us</h1> <br/>
              FitQuest is an app designed to help users achieve their fitness goals and compete with friends.
              It provides a platform for users to track their workouts, set goals, and monitor their progress.
              With FitQuest, users can create personalized workout plans, access a library of exercises,
              and join challenges to stay motivated and engaged. Whether you're a beginner or an experienced fitness enthusiast, FitQuest is here to support you
              on your fitness journey and help you reach your full potential.
          </Description>      
          <ImgContainer>
          <img src = "FitQuestLogo.jpg"/>
          </ImgContainer> 
        </DescriptionAndImageContainer>
        <h1>Fitness</h1>
        <DescriptionAndImageContainer>
            <Description>
            <h1>The Fitness Experience</h1> <br/>
              The fitness challenge functionality of the FitQuest app allows users to track their fitness data and compete in challenges. 
              Users can set goals, monitor their progress, and participate in various challenges to stay motivated and engaged. 
              The app provides a platform for users to create personalized workout plans, access a library of exercises, and join challenges with friends or other users. 
              Whether you're a beginner or an experienced fitness enthusiast, FitQuest is designed to help you achieve your fitness goals and reach your full potential.
            </Description>
        </DescriptionAndImageContainer>
      </BodyContainer>



      </ParentContainer>

  

    </>
  );
}

// Organizing into various containers, somewhat messy as of 2/13

const TitleContainer = styled.div`
  
  font-size: 2.5em;
  align-items: center;
  justify-content: center;
  text-align: center;
  background-color: #70d158; //light-ish green


  
`;




const BodyContainer = styled.div`
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  align-items: center;
  height: 100vh;
  background-color: #70d158; //light-ish green
  position: relative;

`;

const DescriptionAndImageContainer = styled.div`
  margin-top: 6vw;
  margin-bottom: 12vw;
  display: flex;
  justify-content: space-between;
`;


const ImgContainer = styled.div`
  display: inline-block;
  border-radius: 3%;
  transform: scale(1.2);
  box-shadow: 0 0 10px rgba(0, 0, 0, .3);      
  margin-bottom: 0vw;
  margin-top: 0vw;                       
  margin-right: 10vw;
  background-color: #042131;
  padding: .5vw;
`;


const Description = styled.div`
  height: 20w;
  width: 50%;
   background-color: #2aad09;
   box-shadow: 0 0 10px rgba(0, 0, 0, .3); 
  border-radius: 3%;
  margin-right: 2vw;
  margin-left: .1vw;
  padding: 2vw;
  font-family: 'Roboto', sans-serif;
`;




// Need to make good functional homepage

// start with a textbox description of the app, need some nice styling