import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";               
import styled from 'styled-components';


import NavBar from "@/components/NavBar";



// importing for a link to another page
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
// npm run dev


// Set all styled components 
const Container = styled.div`
  color: green;
`




const ParentContainer = styled.div`
*{
  // padding: 0;
  flex-direction: row;
}
`


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* This h1 is a LINK to the test JS file  */}
      {/* {/* <h1><Link href="/test">Click to go to Dashboard</Link> </h1> */}

      <ParentContainer>
        <NavBar/>
        <h2><Link href="/login">Click to go to Login Page</Link> </h2>
      <Container>CMPSC 263 DEMO</Container> 
      </ParentContainer>

  

    </>
  );
}

