require('dotenv').config();
import Head from "next/head";
import styled from 'styled-components';
import {useState, useEffect, useRef} from 'react';
// import Day_Quote from "@/components/Day_Quote";
import firebase_app from "@/library/firebaseConfig";
import database from "@/library/firebaseConfig";
import NavBar from "@/components/NavBar";



export default function Home() {
  const [quote, setQuote] = useState("Motivational Quote Here");
  useEffect(() => {
    fetchQuotes();
  }, []);
// Pulls a quote from the api (set as the 0th return now, seems to change on every refresh, gotta watch limit)
// ASK WHY environment variable is not working, api key in use directly does work but process env not

var category = 'fitness';
const fetchQuotes = async () => {
  try {
    console.log("Fetching the quote")
    const response = await fetch('/api/quote');
    const data = await response.json();
    setQuote(data.quote);
    console.log("Fetched!");
  } catch (error) {
    console.error('Error fetching quotes:', error);
  }
}


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* This h1 is a LINK to the test JS file  */}
      {/* {/* <h1><Link href="/test">Click to go to Dashboard</Link> </h1> */}
      {/* <Day_Quote/> */}

      <ParentContainer>
        <NavBar/>

      <TitleContainer>Welcome To FitQuest!</TitleContainer>
      <BodyContainer>
        <BannerImgContainer> 
          <img src= "Fitness_Stock_Image_2.jpg"/>
        </BannerImgContainer>
        <Description>
            <h1>About Us</h1> <br/>
            FitQuest is an app designed to help users achieve their fitness goals and compete with friends.
            It provides a platform for users to track their workouts, set goals, and monitor their progress.
            With FitQuest, users can create personalized workout plans, access a library of exercises,
            and join challenges to stay motivated and engaged. Whether you're a beginner or an experienced fitness enthusiast, FitQuest is here to support you
            on your fitness journey and help you reach your full potential.
        </Description>  
        <Description><h1> Quote Of The Day</h1> <br/> {quote} </Description>    
        <TitleContainer>Fitness</TitleContainer>
        <br/>
        <DescriptionAndImageContainer>
          <StyledLink href="/Fitness">
              <ImgContainer>
                <img src = "FitQuestLogo.jpg"/>
              </ImgContainer> 
          </StyledLink>
          <br/>
          <Description>
            {/* <TitleContainer>The Fitness Experience</TitleContainer>  */}
            The FitQuest app offers a fitness challenge feature where users can track their progress, set goals, and engage in competitions. It includes personalized workout plans, 
            a library of exercises, and the option to join challenges with others, catering to both beginners and seasoned fitness enthusiasts aiming to reach their fitness potential.
          </Description>
        </DescriptionAndImageContainer>
      </BodyContainer>



      </ParentContainer>

  

    </>
  );
}

// Organizing into various containers, somewhat messy as of 2/13 
// Colors used: 
// original background: #70d158; //light-ish green
// new background: #BAEDC1 // Magand (light green)

// old description background: #2aad09
// new description background: #082834

// Set all styled components 
const Container = styled.div`
  color: green;
`



const ParentContainer = styled.div`
  font-family: 'Roboto', sans-serif;
  // color: white;
  background-color: #f2f2e6;  //very light grey
  height: 100%;
  color: Navy;
`

const StyledLink = styled.a`
  // color: inherit;
  // text-decoration: none;
  height: 40vw;
`;

const TitleContainer = styled.div`
  font-size: 5.0vw;
  padding: 3vw;
  align-items: center;
  justify-content: center;
  text-align: center;
  font-weight: bold;
`;

const BodyContainer = styled.div`
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  align-items: center;
  height: 100%;
  // background-color: #37de3d; //light-ish green
  background-color: #f2f2e6;  //very light grey

  position: relative;
  
  
`;



const DescriptionAndImageContainer = styled.div`
  // margin-top: 6vw;
  // margin-bottom: 12vw;
  height: 100vw;
  // width: 50%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  justfiy-content: center;
  overflow: hidden;  

  `;



  const ImgContainer = styled.div`
    display: flex;
    justify-content: center;
    border-radius: 3%;
    transform: scale(1.1);
    margin-top: 2vw;
    box-shadow: 0 0 10px rgba(0, 0, 0, .3); 
    width: 20vw;
    height: 20vw;     
    background-color: #042131;
    padding: 3vw;
    // border-top-left-radius: 10px;
    // border-top-right-radius: 10px;
  `;

  const BannerImgContainer = styled.div`
  display: flex;
  justify-content: center;
  align_item
  border-radius: 3%;
  border: 1px solid black;
  transform: scale(1.2);
  // box-shadow: 0 0 10px rgba(0, 0, 0, .3); 
  // width: 20vw;
  // height: 20vw;     
  margin-bottom: 5vw;
  margin-top: 5vw;                       
  // margin-right: 10vw;
  // background-color: #042131;
  padding: 3vw;
`;



const Description = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 120vh;
  // background-color: #067d0a;
  color: Navy;   
  boxwidth-shadow: 0 0 10px rgba(0, 0, 0, .3); 
  border-radius: 3%;
  margin-right: 2vw;
  margin-left: .1vw;
  width: 50%;
  padding: 3vw;
  font-size: 2.4vw;
  font-family: 'Roboto', sans-serif;
`;
